sudo: required

language: cpp

dist: xenial

env:
  global:
    - CODECOV_TOKEN="2f8f46e7-953b-4d71-8529-4f7f4894eeef"

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - gcc-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - COMPILE_FLAGS="-DENABLE_TESTING=ON"
        - BUILD_TYPE="Debug"
        - CODE_COVERAGE="ON"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - gcc-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
        - COMPILE_FLAGS="-DENABLE_TESTING=ON"
        - BUILD_TYPE="Debug"
        - CODE_COVERAGE="ON"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - gcc-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - COMPILE_FLAGS="-DCXXTEST_ADD_PERFORMANCE=ON"
        - BUILD_TYPE="Release"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - gcc-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
        - COMPILE_FLAGS="-DCXXTEST_ADD_PERFORMANCE=ON"
        - BUILD_TYPE="Release"

before_script:
  - sudo apt-get install build-essential
  - |
    if [[ "${CODE_COVERAGE}" = "ON" ]]; then
    sudo apt-get install lcov
    fi
  - cmake --version
  - eval "${MATRIX_EVAL}"
  
install:
  - sudo pip install codecov
  - echo "${TRAVIS_BUILD_DIR}"
  - echo "${TRAVIS_OS_NAME}"
  - ls
  - pwd
  - git branch -a
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}

script:
  - cd "${TRAVIS_BUILD_DIR}"
  - mkdir build
  - cd build
  - pwd
  - cmake "${COMPILE_FLAGS}" "-DCODE_COVERAGE=${CODE_COVERAGE}" "-DCMAKE_BUILD_TYPE=${BUILD_TYPE}"  ..
  - make
  - make test ARGS="-V"
  - echo "CODE COVERAGE ${CODE_COVERAGE}"
  - |
    if [[ "${CODE_COVERAGE}" == "ON" ]]; then
    make coverage
    make coverage-upload
    fi
