sudo: required

language: cpp

compiler:
  - gcc
  - clang

install:
  - echo "${TRAVIS_BUILD_DIR}"
  - echo "${TRAVIS_OS_NAME}"
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}

  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
    CMAKE_URL="http://www.cmake.org/files/v3.4/cmake-3.4.1.tar.gz"
    mkdir cmake && wget ${CMAKE_URL} && tar -xzf cmake-3.4.1.tar.gz && cd cmake-3.4.1/ && ./configure >/dev/null && make >/dev/null && sudo make install
    fi

before_script:
  - cd ~
  - git clone https://github.com/JoshuaSBrown/CourseGrainSites.git
  - cd CourseGrainSites
  - git checkout -b current_commit


script:
  - mkdir build
  - cd build
  - pwd
  - cmake -DENABLE_TESTING=ON ..
  - make
  - make test ARGS="-V"
