sudo: required

language: cpp

dist: trusty

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - gcc-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - gcc-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"


before_script:
  - sudo apt-get install build-essential
  - eval "${MATRIX_EVAL}"
  
install:
  - echo "${TRAVIS_BUILD_DIR}"
  - echo "${TRAVIS_OS_NAME}"
  - ls
  - pwd
  - git branch -a
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
    CMAKE_URL="http://www.cmake.org/files/v3.4/cmake-3.4.1.tar.gz"
    mkdir cmake && wget ${CMAKE_URL} && tar -xzf cmake-3.4.1.tar.gz && cd cmake-3.4.1/ && ./configure >/dev/null && make >/dev/null && sudo make install >/dev/null
    fi

script:
  - cd "${TRAVIS_BUILD_DIR}"
  - mkdir build
  - cd build
  - pwd
  - cmake -DENABLE_TESTING=ON ..
  - make
  - make test ARGS="-V"
